name: Run MLB Model Daily

# trigger refresh

permissions:
  contents: write

on:
  schedule:
    - cron: '16 14 * * *'
  workflow_dispatch:

jobs:
  run-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run settle bets
      run: python settle_bets_github.py

    - name: Pull props
      env:
        ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
      run: python pull_props_github.py

    - name: Update dataset
      run: python update_dataset_github.py

    - name: Run live predictions
      run: python live_predictions_github.py

    - name: Commit updated files
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add *.csv
        git commit -m "update outputs" || echo "No changes to commit"
        git push
